import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

class Autogenerated {
  String index;
  String mosabeha;
  String settings;
  String intro;
  String morning;
  String evening;
  String wakeup;
  String toilet;
  String ablution;
  String dress;
  String homeEnter;
  String mosque;
  String azan;
  String prayer;
  String ruqou;
  String sojood;
  String qunoot;
  String sleeping;
  String casualThings;
  String illness;
  String death;
  String funeralPrayer;
  String fasting;
  String haj;
  String travelling;
  String jihad;
  String eating;
  String sneeze;
  String marriage;
  String overheadThings;
  String differentAzkar;
  String fromQuran;
  String fromSunna;
  String majlis;
  String absoluteDoaa;
  String absoluteZikr;
  static Map<String, dynamic> json;
  static Future<void> load(String path) async {
    final strJson = await rootBundle.loadString(path);
    json = jsonDecode(strJson);
  }

  Autogenerated(
      {this.index,
      this.mosabeha,
      this.settings,
      this.intro,
      this.morning,
      this.evening,
      this.wakeup,
      this.toilet,
      this.ablution,
      this.dress,
      this.homeEnter,
      this.mosque,
      this.azan,
      this.prayer,
      this.ruqou,
      this.sojood,
      this.qunoot,
      this.sleeping,
      this.casualThings,
      this.illness,
      this.death,
      this.funeralPrayer,
      this.fasting,
      this.haj,
      this.travelling,
      this.jihad,
      this.eating,
      this.sneeze,
      this.marriage,
      this.overheadThings,
      this.differentAzkar,
      this.fromQuran,
      this.fromSunna,
      this.majlis,
      this.absoluteDoaa,
      this.absoluteZikr});

  Autogenerated.fromJson() {
    index = json['index'];
    mosabeha = json['mosabeha'];
    settings = json['settings'];
    intro = json['intro'];
    morning = json['morning'];
    evening = json['evening'];
    wakeup = json['wakeup'];
    toilet = json['toilet'];
    ablution = json['ablution'];
    dress = json['dress'];
    homeEnter = json['home-enter'];
    mosque = json['mosque'];
    azan = json['azan'];
    prayer = json['prayer'];
    ruqou = json['ruqou'];
    sojood = json['sojood'];
    qunoot = json['qunoot'];
    sleeping = json['sleeping'];
    casualThings = json['casual-things'];
    illness = json['illness'];
    death = json['death'];
    funeralPrayer = json['funeral-prayer'];
    fasting = json['fasting'];
    haj = json['haj'];
    travelling = json['travelling'];
    jihad = json['jihad'];
    eating = json['eating'];
    sneeze = json['sneeze'];
    marriage = json['marriage'];
    overheadThings = json['overhead-things'];
    differentAzkar = json['different-azkar'];
    fromQuran = json['from-quran'];
    fromSunna = json['from-sunna'];
    majlis = json['majlis'];
    absoluteDoaa = json['absolute-doaa'];
    absoluteZikr = json['absolute-zikr'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['index'] = this.index;
    data['mosabeha'] = this.mosabeha;
    data['settings'] = this.settings;
    data['intro'] = this.intro;
    data['morning'] = this.morning;
    data['evening'] = this.evening;
    data['wakeup'] = this.wakeup;
    data['toilet'] = this.toilet;
    data['ablution'] = this.ablution;
    data['dress'] = this.dress;
    data['home-enter'] = this.homeEnter;
    data['mosque'] = this.mosque;
    data['azan'] = this.azan;
    data['prayer'] = this.prayer;
    data['ruqou'] = this.ruqou;
    data['sojood'] = this.sojood;
    data['qunoot'] = this.qunoot;
    data['sleeping'] = this.sleeping;
    data['casual-things'] = this.casualThings;
    data['illness'] = this.illness;
    data['death'] = this.death;
    data['funeral-prayer'] = this.funeralPrayer;
    data['fasting'] = this.fasting;
    data['haj'] = this.haj;
    data['travelling'] = this.travelling;
    data['jihad'] = this.jihad;
    data['eating'] = this.eating;
    data['sneeze'] = this.sneeze;
    data['marriage'] = this.marriage;
    data['overhead-things'] = this.overheadThings;
    data['different-azkar'] = this.differentAzkar;
    data['from-quran'] = this.fromQuran;
    data['from-sunna'] = this.fromSunna;
    data['majlis'] = this.majlis;
    data['absolute-doaa'] = this.absoluteDoaa;
    data['absolute-zikr'] = this.absoluteZikr;
    return data;
  }
}
